# Generated by Django 3.1 on 2022-08-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=12)),
                ('lastname', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=20)),
            ],
        ),
    ]
